- name: Apply Redis database namespace manifest to the cluster.
  community.kubernetes.k8s:
    state: present
    src: /Users/moi/work/glitzup/saleor-tf-k8s/platform/resources/manifests/namespaces/redis.yaml

- name: Apply Redis database volume manifest to the cluster.
  community.kubernetes.k8s:
    state: present
    src: /Users/moi/work/glitzup/saleor-tf-k8s/platform/redis/manifests/database/volume.yaml

- name: Apply Redis database configmap manifest to the cluster.
  community.kubernetes.k8s:
    state: present
    src: /Users/moi/work/glitzup/saleor-tf-k8s/platform/redis/manifests/database/config.yaml

- name: Apply Redis database service manifest to the cluster.
  community.kubernetes.k8s:
    state: present
    src: /Users/moi/work/glitzup/saleor-tf-k8s/platform/redis/manifests/database/service.yaml

- name: Apply Redis database deployment manifest to the cluster.
  community.kubernetes.k8s:
    state: present
    src: /Users/moi/work/glitzup/saleor-tf-k8s/platform/redis/manifests/database/deployment.yaml
